services:
  mongodb:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - backend

  redis:
    networks:
      - backend
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  api:
    networks:
      - backend
    build: .
    container_name: api
    ports:
      - "5050:5050"
    environment:
      - MONGO_URL=mongodb://mongodb:27017/ostad-db
      - MONGO_INITDB_ROOT_USERNAME=ostad
      - MONGO_INITDB_ROOT_PASSWORD=ostad
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mongodb
      - redis

volumes:
  mongodb_data:

networks:
  backend:
    driver: bridge
