apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  VITE_API_BASE_URL: "http://192.168.0.101:5050"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-deploy
  labels:
    app: capstone
spec:
  replicas: 3
  selector:
    matchLabels:
      app: capstone
  template:
    metadata:
      labels:
        app: capstone
    spec:
      containers:
        - name: capstone-ctr
          image: rootovertwo/capstone-project-frontend:latest
          env:
            - name: VITE_API_BASE_URL_ARG
              value: http://13.223.55.82:5050
          ports:
            - containerPort: 5173
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: capstone-service
spec:
  selector:
    app: capstone
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5173
      nodePort: 30007
  type: NodePort
